# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nradio.ui'
#
# Created: Sat Jan 26 11:22:06 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_nradio(object):
    def setupUi(self, nradio):
        nradio.setObjectName(_fromUtf8("nradio"))
        nradio.resize(800, 602)
        self.centralwidget = QtGui.QWidget(nradio)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 551))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.playlist = QtGui.QTreeWidget(self.tab)
        self.playlist.setGeometry(QtCore.QRect(10, 10, 751, 401))
        self.playlist.setObjectName(_fromUtf8("playlist"))
        self.add_new = QtGui.QPushButton(self.tab)
        self.add_new.setGeometry(QtCore.QRect(10, 440, 71, 27))
        self.add_new.setObjectName(_fromUtf8("add_new"))
        self.delete_button = QtGui.QPushButton(self.tab)
        self.delete_button.setGeometry(QtCore.QRect(150, 440, 71, 27))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.play_button = QtGui.QPushButton(self.tab)
        self.play_button.setGeometry(QtCore.QRect(10, 470, 71, 27))
        self.play_button.setObjectName(_fromUtf8("play_button"))
        self.pause_button = QtGui.QPushButton(self.tab)
        self.pause_button.setGeometry(QtCore.QRect(80, 470, 71, 27))
        self.pause_button.setObjectName(_fromUtf8("pause_button"))
        self.stop_button = QtGui.QPushButton(self.tab)
        self.stop_button.setGeometry(QtCore.QRect(150, 470, 71, 27))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.player_seek = phonon.Phonon.SeekSlider(self.tab)
        self.player_seek.setGeometry(QtCore.QRect(280, 440, 411, 24))
        self.player_seek.setObjectName(_fromUtf8("player_seek"))
        self.player_volume = phonon.Phonon.VolumeSlider(self.tab)
        self.player_volume.setGeometry(QtCore.QRect(280, 470, 411, 32))
        self.player_volume.setObjectName(_fromUtf8("player_volume"))
        self.seek_locked = QtGui.QCheckBox(self.tab)
        self.seek_locked.setGeometry(QtCore.QRect(250, 440, 21, 20))
        self.seek_locked.setText(_fromUtf8(""))
        self.seek_locked.setObjectName(_fromUtf8("seek_locked"))
        self.volume_locked = QtGui.QCheckBox(self.tab)
        self.volume_locked.setEnabled(True)
        self.volume_locked.setGeometry(QtCore.QRect(250, 480, 21, 20))
        self.volume_locked.setText(_fromUtf8(""))
        self.volume_locked.setObjectName(_fromUtf8("volume_locked"))
        self.add_m3u = QtGui.QPushButton(self.tab)
        self.add_m3u.setGeometry(QtCore.QRect(80, 440, 71, 27))
        self.add_m3u.setObjectName(_fromUtf8("add_m3u"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(700, 420, 59, 15))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(700, 470, 59, 15))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lcd1 = QtGui.QLabel(self.tab)
        self.lcd1.setGeometry(QtCore.QRect(710, 440, 59, 15))
        self.lcd1.setObjectName(_fromUtf8("lcd1"))
        self.lcd2 = QtGui.QLabel(self.tab)
        self.lcd2.setGeometry(QtCore.QRect(710, 490, 59, 15))
        self.lcd2.setObjectName(_fromUtf8("lcd2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 741, 80))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 92, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 50, 131, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 59, 15))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 110, 741, 221))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 301, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(80, 60, 59, 15))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.jingle_time = QtGui.QLineEdit(self.groupBox_2)
        self.jingle_time.setGeometry(QtCore.QRect(20, 50, 51, 25))
        self.jingle_time.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.jingle_time.setObjectName(_fromUtf8("jingle_time"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 341, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(80, 110, 59, 15))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.jingleXXX = QtGui.QLineEdit(self.groupBox_2)
        self.jingleXXX.setGeometry(QtCore.QRect(20, 100, 51, 25))
        self.jingleXXX.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.jingleXXX.setObjectName(_fromUtf8("jingleXXX"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 101, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(80, 160, 131, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.jingle_volume = QtGui.QLineEdit(self.groupBox_2)
        self.jingle_volume.setGeometry(QtCore.QRect(20, 150, 51, 25))
        self.jingle_volume.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.jingle_volume.setObjectName(_fromUtf8("jingle_volume"))
        self.save_settings = QtGui.QPushButton(self.groupBox_2)
        self.save_settings.setGeometry(QtCore.QRect(20, 180, 92, 27))
        self.save_settings.setObjectName(_fromUtf8("save_settings"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(120, 190, 221, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.jingle_start = QtGui.QPushButton(self.groupBox_2)
        self.jingle_start.setGeometry(QtCore.QRect(510, 30, 92, 27))
        self.jingle_start.setObjectName(_fromUtf8("jingle_start"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 751, 191))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 131, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 50, 51, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 80, 51, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        nradio.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(nradio)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        nradio.setStatusBar(self.statusbar)

        self.retranslateUi(nradio)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(nradio)

    def retranslateUi(self, nradio):
        nradio.setWindowTitle(QtGui.QApplication.translate("nradio", "nradio", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setWhatsThis(QtGui.QApplication.translate("nradio", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.playlist.headerItem().setText(0, QtGui.QApplication.translate("nradio", "Wykonawca", None, QtGui.QApplication.UnicodeUTF8))
        self.playlist.headerItem().setText(1, QtGui.QApplication.translate("nradio", "Tytuł", None, QtGui.QApplication.UnicodeUTF8))
        self.playlist.headerItem().setText(2, QtGui.QApplication.translate("nradio", "Czas", None, QtGui.QApplication.UnicodeUTF8))
        self.playlist.headerItem().setText(3, QtGui.QApplication.translate("nradio", "ETA", None, QtGui.QApplication.UnicodeUTF8))
        self.playlist.headerItem().setText(4, QtGui.QApplication.translate("nradio", "Url", None, QtGui.QApplication.UnicodeUTF8))
        self.add_new.setText(QtGui.QApplication.translate("nradio", "add", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_button.setText(QtGui.QApplication.translate("nradio", "remove", None, QtGui.QApplication.UnicodeUTF8))
        self.play_button.setText(QtGui.QApplication.translate("nradio", "play", None, QtGui.QApplication.UnicodeUTF8))
        self.pause_button.setText(QtGui.QApplication.translate("nradio", "pause", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setText(QtGui.QApplication.translate("nradio", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.add_m3u.setText(QtGui.QApplication.translate("nradio", "add m3u", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("nradio", "player:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("nradio", "jingle za:", None, QtGui.QApplication.UnicodeUTF8))
        self.lcd1.setText(QtGui.QApplication.translate("nradio", "00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.lcd2.setText(QtGui.QApplication.translate("nradio", "00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("nradio", "Player", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("nradio", "Opcje pliku", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("nradio", "wybierz plik", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("nradio", "Aktualnie wybrany:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("nradio", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("nradio", "Opcje odtwarzania", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("nradio", "Co ile sekund odpalac jingle? (0 = na zadanie)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("nradio", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("nradio", "Czas na wyciszenie muzyki przed odpaleniem jingle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("nradio", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("nradio", "Glośność jignle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("nradio", "% głośności playera", None, QtGui.QApplication.UnicodeUTF8))
        self.jingle_volume.setText(QtGui.QApplication.translate("nradio", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.save_settings.setText(QtGui.QApplication.translate("nradio", "ZAPISZ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("nradio", "PAMIĘTAJ O ZAPISANIU USTAWIEŃ!", None, QtGui.QApplication.UnicodeUTF8))
        self.jingle_start.setText(QtGui.QApplication.translate("nradio", "ODPAL", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("nradio", "Ustawienia jingle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("nradio", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("nradio", "Miejsce zapisu opcji:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("nradio", "zmień", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("nradio", "zapisz", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("nradio", "Ustawienia", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
